apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx
